buildscript {
    repositories {
        gradlePluginPortal()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath 'gradle.plugin.com.github.sherter.google-java-format:google-java-format-gradle-plugin:0.9'
        classpath 'net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin:5.1.0'
        classpath 'com.vanniktech:gradle-maven-publish-plugin:0.37.0'
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
    }
}

subprojects {
    apply plugin: 'com.github.sherter.google-java-format'
    apply plugin: 'com.android.library'
    apply plugin: 'net.ltgt.errorprone'

    googleJavaFormat {
        toolVersion = '1.5'
        options style: 'AOSP'
    }

    dependencies {
        // NOTE: Updating ErrorProne introduces new checks that may cause the build to fail. Pin to a
        // specific version to control these updates.
        errorprone("com.google.errorprone:error_prone_core:2.42.0")
        annotationProcessor("com.google.errorprone:error_prone_core:2.42.0")
        testAnnotationProcessor("com.google.errorprone:error_prone_core:2.42.0")
    }

    group = 'com.android.volley'
    version = findProperty('VERSION_NAME') ?: '1.2.2-SNAPSHOT'

    android {
        useLibrary 'org.apache.http.legacy'

        compileSdk 34

        defaultConfig {
            minSdkVersion 8
        }

        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.errorprone.enabled = true
        options.errorprone {
            check("ParameterComment", net.ltgt.gradle.errorprone.CheckSeverity.ERROR)
            // TODO: Fix violations introduced by upgrading ErrorProne and re-enable these checks.
            disable("BadImport")
            disable("DirectInvocationOnMock")
            disable("EffectivelyPrivate")
            disable("EmptyBlockTag")
            disable("EmptyCatch")
            disable("EnumOrdinal")
            disable("EscapedEntity")
            disable("Finalize")
            disable("InlineMeSuggester")
            disable("JavaUtilDate")
            disable("MissingImplementsComparable")
            disable("MissingSummary")
            disable("MixedMutabilityReturnType")
            disable("MockNotUsedInProduction")
            disable("NonApiType")
            disable("StringCharset")
            disable("UnnecessaryStringBuilder")
            disable("UnusedMethod")
            disable("UnusedVariable")
        }
        options.compilerArgs << "-Xlint:unchecked" << "-Werror"
    }

    if (it.name != 'testing') {
        apply from: '../publish.gradle'
    }
}
