apply plugin: 'com.vanniktech.maven.publish'

afterEvaluate {
    mavenPublishing {
        coordinates(project.group.toString(), project.artifactId.toString(), project.version.toString())

        publishToMavenCentral()

        pom {
            name = project.pomName
            description = project.pomDescription
            url = 'https://github.com/google/volley'
            licenses {
                license {
                    name = "The Apache License, Version 2.0"
                    url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                }
            }
            scm {
                connection = 'scm:git:git://github.com/google/volley.git'
                developerConnection = 'scm:git:ssh://git@github.com/google/volley.git'
                url = 'https://github.com/google/volley'
            }
            developers {
                developer {
                    name = 'The Volley Team'
                    email = 'noreply+volley@google.com'
                }
            }
        }
    }
}
